# Travis CI configuration file.

language: php

php:
    - 5.2

env:
    - TRAVISCI_RUN=phpunit WP_VERSION=latest WP_MULTISITE=0
    - TRAVISCI_RUN=phpunit WP_VERSION=latest WP_MULTISITE=1
    - TRAVISCI_RUN=phpunit WP_VERSION=3.8 WP_MULTISITE=0
    - TRAVISCI_RUN=phpunit WP_VERSION=3.8 WP_MULTISITE=1

matrix:
  include:
    - php: 5.2
      env: TRAVISCI_RUN=codesniff
  exclude:
    - php: 5.6
      env: TRAVISCI_RUN=phpunit WP_VERSION=3.8 WP_MULTISITE=0
    - php: 5.6
      env: TRAVISCI_RUN=phpunit WP_VERSION=3.8 WP_MULTISITE=1
  allow_failures:
    - php: 5.6
  fast_finish: true

before_install:
    - export WP_TESTS_DIR=/tmp/wordpress-tests/
    - export PLUGIN_DIR=$(pwd)
    - export PLUGIN_SLUG=$(basename $(pwd) | sed 's/^wp-//')
    - export PHPCS_DIR=/tmp/phpcs
    - export PHPCS_GITHUB_SRC=squizlabs/PHP_CodeSniffer
    - export PHPCS_GIT_TREE=master
    - export WPCS_GITHUB_SRC=WordPress-Coding-Standards/WordPress-Coding-Standards
    - export WPCS_GIT_TREE=master
    - export WPCS_STANDARD=$(if [ -e phpcs.ruleset.xml ]; then echo phpcs.ruleset.xml; else echo WordPress; fi)
    - if [ -e .ci-env.sh ]; then source .ci-env.sh; fi

before_script:
    - >
        if [ $TRAVISCI_RUN == phpunit ]; then
            wget -O /tmp/install-wp-tests.sh https://raw.githubusercontent.com/wp-cli/wp-cli/master/templates/install-wp-tests.sh
            bash /tmp/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
            cd /tmp/wordpress/wp-content/plugins
            ln -s $PLUGIN_DIR $PLUGIN_SLUG
            cd $PLUGIN_DIR
        fi
    - >
        if [ $TRAVISCI_RUN == codesniff ]; then
            mkdir -p $PHPCS_DIR && curl -L https://github.com/$PHPCS_GITHUB_SRC/archive/$PHPCS_GIT_TREE.tar.gz | tar xvz --strip-components=1 -C $PHPCS_DIR
            mkdir -p $PHPCS_DIR/CodeSniffer/Standards/WordPress && curl -L https://github.com/$WPCS_GITHUB_SRC/archive/$WPCS_GIT_TREE.tar.gz | tar xvz --strip-components=1 -C $PHPCS_DIR/CodeSniffer/Standards/WordPress
            npm install -g jshint
        fi

script: ./tools/bin/travis-script.sh
